/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaselogin;

import java.sql.SQLException;
import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Kesh
 */
public class Surephrase extends javax.swing.JFrame {

    char [] temp;
    RegDb db ;

    Login l;
    /**
     * Creates new form Surephrase
     */
    public Surephrase(String username) throws SQLException {
        db=new RegDb();
        initComponents();
        temp=createSurePhrase(username);

    }

    public Surephrase(){

    }
    public void init(Login l){
        this.l = l;
    }

    static Random rand= new Random();

    public char [] createSurePhrase(String phrase){
        //create a char array of the sure phrase
        char p[] = new char[phrase.length()];

        //enter values in both the arrays
        for(int i = 0; i < phrase.length();i++){
            if(phrase.charAt(i)==' '){
                p[i] = '$';
            }
            else{
                p[i] = phrase.charAt(i);
            }
        }

        //print the max length of the array
        System.out.println("max length "+((p.length)));
        //create a random number of values to leave out from the temp array and print it
        int numberOfMissingValues = rand.nextInt(phrase.length())+1;
        System.out.println("missing val "+numberOfMissingValues);

        //create a temp char array to chnage
        char tempPhrase[] = new char[numberOfMissingValues];

        //change random unique values of the temp array to  a '_'
        for(int i =  0; i < numberOfMissingValues; i++){

            int position = rand.nextInt(p.length);

            tempPhrase[i] = p[position];
        }

        for(int i = 0; i < tempPhrase.length;i++){
            System.out.print(tempPhrase[i]);
        }
        return tempPhrase;
    }

    public void checkSurePhrase(char [] tempPhrase){


        //System.out.println("\nPlease enter surephrase");

        String u = surephraseTextField.getText();

        char[]checkPhrase = new char [u.length()];

        for(int i = 0; i < u.length(); i++) {

            checkPhrase[i] = u.charAt(i);
        }

        boolean corr = true;

        for(int x = 0; x < u.length(); x++){
            if (tempPhrase[x]!=checkPhrase[x]){
                corr = false;
                break;
            }
        }

        if(corr){
            System.out.println("correct");
            setVisible(false);
            l.risk = 1;
            l.r.update(l.risk);
        }
        else{
            l.risk = 3;
            l.r.update(l.risk);
            JOptionPane.showMessageDialog(this, "Incorrect Surephrase!", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("wrong");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SurephraseHeader = new javax.swing.JLabel();
        SurephrasePrompt = new javax.swing.JLabel();
        surephraseTextField = new javax.swing.JTextField();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Surephrase");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        SurephraseHeader.setFont(new java.awt.Font("Cooper Black", 2, 24)); // NOI18N
        SurephraseHeader.setForeground(new java.awt.Color(240, 0, 0));
        SurephraseHeader.setText("Surephrase");

        SurephrasePrompt.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        SurephrasePrompt.setForeground(new java.awt.Color(250, 0, 0));
        SurephrasePrompt.setText("Enter surephrase:");

        continueButton.setBackground(new java.awt.Color(240, 0, 0));
        continueButton.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(SurephrasePrompt)
                                                .addGap(18, 18, 18)
                                                .addComponent(surephraseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(127, 127, 127)
                                                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(56, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SurephraseHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(SurephraseHeader)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SurephrasePrompt)
                                        .addComponent(surephraseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:

        checkSurePhrase(temp);
    }//GEN-LAST:event_continueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Surephrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Surephrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Surephrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Surephrase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Surephrase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SurephraseHeader;
    private javax.swing.JLabel SurephrasePrompt;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField surephraseTextField;
    // End of variables declaration//GEN-END:variables
}
